### ISSUE TITLE
Compilation with g++-4.6

### ISSUE THREAD

**Issue by bjornbugge** [Shark-ML/Remora#3]
Remora doesn't compile on g++-4.6 due its lack of support for some C++11 features.  The use of template alias is not supported, and the use of "this" outside a member function (in inferred return types) is also not supported (like in "	auto operator()(IndexExpression const& i) const -> decltype(this->expression()(i)){")

**Comment by Ulfgard** [comment]
The latter is hard to wontfix. Different compilers choke depending on whether this is there or not.

________________________________

**Comment by Ulfgard** [comment]
fixed :)

**Comment by bjornbugge** [comment]
:fireworks:
